# Generated by Django 5.1.2 on 2024-11-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_logisticsprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.PositiveIntegerField()),
                ('icon_class', models.CharField(max_length=50)),
                ('background_class', models.CharField(default='bg-primary', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('contact_title', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fact_boxes', models.ManyToManyField(related_name='sections', to='app.factbox')),
            ],
        ),
    ]
